[package]
name = "ferromq-bridge-ingress-kafka"
version.workspace = true
description = "Bridge remote KAFKA in ingress mode."
repository.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ferromq = { workspace = true, features = ["plugin", "msgstore"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }
serde_json.workspace = true
log.workspace = true
async-trait.workspace = true
anyhow.workspace = true
bytestring.workspace = true
bytes.workspace = true
event-notify = "0.1.1"
rdkafka = { version = "0.38", features = ["cmake-build"] }
rdkafka-sys = "=4.9.0"